-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 05:33:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ciclos_propedeuticos_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciclos_propedeuticos_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciclos_propedeuticos_2` DEFAULT CHARACTER SET utf8 ;
USE `ciclos_propedeuticos_2` ;

-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`chats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT 'nombre',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT 'ultimima actualizzacion',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '																																																	';


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `second_last_name` VARCHAR(50) NULL DEFAULT NULL,
  `card_id` VARCHAR(13) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(10) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rol_rol_id` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_rol_rol_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `ciclos_propedeuticos_2`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = '																																																	';


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `name` VARCHAR(50) NOT NULL COMMENT 'nombre',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT 'ultimima actualizzacion',
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_posts_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ciclos_propedeuticos_2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `text` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_chat` (`post_id` ASC) VISIBLE,
  INDEX `fk_comments_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `comments_post_id_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `ciclos_propedeuticos_2`.`posts` (`id`),
  CONSTRAINT `fk_comments_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ciclos_propedeuticos_2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`cycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`cycle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `chat_id` INT(11) NOT NULL,
  `user_send_id` INT(11) NOT NULL,
  `user_recive_id` INT(11) NOT NULL,
  `text` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_chat` (`chat_id` ASC) VISIBLE,
  INDEX `fk_user_send_id_idx` (`user_send_id` ASC) VISIBLE,
  INDEX `fk_user_recive_id_idx` (`user_recive_id` ASC) VISIBLE,
  CONSTRAINT `messages_ibfk_1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `ciclos_propedeuticos_2`.`chats` (`id`),
  CONSTRAINT `fk_user_send_id`
    FOREIGN KEY (`user_send_id`)
    REFERENCES `ciclos_propedeuticos_2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_recive_id`
    FOREIGN KEY (`user_recive_id`)
    REFERENCES `ciclos_propedeuticos_2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`request_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`request_degree` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `from` VARCHAR(45) NULL DEFAULT NULL,
  `degree_project_name` VARCHAR(45) NOT NULL,
  `observation` VARCHAR(255) NULL DEFAULT 'Sin Observaciones',
  `state` TINYINT(1) NULL DEFAULT 1 COMMENT 'estado de la solicitud de grado',
  `degree_date` DATE NULL DEFAULT NULL COMMENT 'fecha de graduacion proporcionada por el coordinador',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`sessions` (
  `session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT(11) UNSIGNED NOT NULL,
  `data` MEDIUMTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ciclos_propedeuticos_2`.`user_cycle_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclos_propedeuticos_2`.`user_cycle_request` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `cycle_id` INT(11) NOT NULL,
  `request_degree_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_cycle_request_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_cycle_request_cycle1_idx` (`cycle_id` ASC) VISIBLE,
  INDEX `fk_user_cycle_request_degree_request1_idx` (`request_degree_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_cycle_request_cycle1`
    FOREIGN KEY (`cycle_id`)
    REFERENCES `ciclos_propedeuticos_2`.`cycle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_cycle_request_degree_request1`
    FOREIGN KEY (`request_degree_id`)
    REFERENCES `ciclos_propedeuticos_2`.`request_degree` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_cycle_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ciclos_propedeuticos_2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
